### ISSUE TITLE
Mention Windows incompatibility in README

### ISSUE THREAD

**Issue by CarbonGhost** [zee-editor/zee#10]
Build fails on Windows because of Termion.

**Comment by pawwkm** [comment]
+1. Just got burned by that too.

**Comment by mcobzarenco** [comment]
Thanks for checking it out -- I assume you installed it using `cargo install zee`? Unfortunately, the version published on crates.io is quite old -- on main branch, for some time the terminal rendering has been handled using [zi](https://github.com/mcobzarenco/zi) which uses [crossterm](https://github.com/crossterm-rs/crossterm) as the backend which should support Windows. I would like to support Linux, Mac and Window, any help with testing would be appreciated.

I'll publish a new version on crates.io as soon as possible

**Comment by LoganDark** [comment]
Why are you trying to use TUI text editors on Windows? If you expect to do anything useful with the terminal you should be using WSL.

**Comment by dhnaranjo** [comment]
> Why are you trying to use TUI text editors on Windows? If you expect to do anything useful with the terminal you should be using WSL at the very least.

Mind your business.

**Comment by mcobzarenco** [comment]
The latest released version replaced the dependency on `termion` with `crossterm` -- I will close this issue as it's specific about `termion`. However, there may be other issues. I would be grateful with any help in testing Windows -- I have no experience building Rust programs on win, but I tried to stay away from any platform specific crates / features :crossed_fingers:
