### ISSUE TITLE
please document required packages to build the sources

### ISSUE THREAD

**Issue by omac777** [zee-editor/zee#19]
I succeeded in building in Fedora Silverblue using the following steps:
```
rpm-ostree install gcc-c++ clang libxcb-devel
systemctl reboot
rustup update
git clone https://github.com/mcobzarenco/zee.git
cd zee
git submodule update --init --recursive
cargo +nightly build --release
```

**Comment by mcobzarenco** [comment]
Thank you for checking out zee & for the report -- absolutely, will do! 

I'm currentlu working on expanding README with detailed build instructions, project goals, a roadmap and website (as well as release a new version on crates.io) -- given the boost in exposure this project recently received :-)

**Comment by mcobzarenco** [comment]
I've added build instructions (and more) to the README. On latest master, I also removed the dependency on the submodules and instead link dynamically to the tree sitter parsers.
