### ISSUE TITLE
Crash on macos: byte index out of bounds

### ISSUE THREAD

**Issue by wizofe** [zee-editor/zee#20]
I get this very often when I try to save a file just with C-x. I managed to replicate it with `BACKTRACE==full`! I hope that helps. It's also messing up my shell afterwards, so I can't use ls, everything looks garbled. I am sorry for the output format but happens because of that :)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Byte index out of bounds: byte index 353, Rope/RopeSlice byte length 352', /Users/wizofe/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.4.1/src/rope.rs:635:41
                                                                                                                     stack backtrace:
              0:        0x104f9370f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d1bc6b9a6cb5b34
                   1:        0x104ea1f7b - core::fmt::write::h64ddbe43c958ac83
                                                                                 2:        0x104f80d2a - std::io::Write::write_fmt::h7e453fd0bb915ce8
                              3:        0x104f8dc71 - std::panicking::default_hook::{{closure}}::hc0a95f88628ea979
                                                                                                                     4:        0x104f8e659 - std::panicking::rust_panic_with_hook::h59a745e8579c1996
                                                                             5:        0x104f93eb9 - std::panicking::begin_panic_handler::{{closure}}::h77c7cdc59f5a8e41
                                                 6:        0x104f93e39 - std::sys_common::backtrace::__rust_end_short_backtrace::hc399a88e87a79fbd
                           7:        0x104f8df85 - _rust_begin_unwind
                                                                        8:        0x1050b297f - core::panicking::panic_fmt::h0686ac972197ca01
                      9:        0x1050b2ad5 - core::result::unwrap_failed::hf19da9b6244b79be
                                                                                              10:        0x104e0176a - ropey::rope::Rope::byte_to_char::h201480d3b347e804
                                                 11:        0x104e296b1 - zee::editor::Editor::draw::{{closure}}::h2dc01d62ac518dce
           12:        0x104e25ed0 - zee::editor::Editor::draw::hd2f779eb09dc3f40
                                                                                  13:        0x104e3a900 - zee::run_editor_ui_loop::h9fa7ef6fb387438c
                             14:        0x104e44075 - zee::start_editor::hc4161be0144edf5d
                                                                                          [1]    40396 abort      RUST_BACKTRACE=full zee bench_corr.py
```

**Comment by mcobzarenco** [comment]
Thanks for checking it out -- I assume you installed it using `cargo install zee`? Unfortunately, the version published on crates.io is quite old -- on main branch, this has been fixed for some time, though there are a few problems! 

I will release a new version on crates.io as soon as possible

**Comment by mcobzarenco** [comment]
> It's also messing up my shell afterwards, so I can't use ls, everything looks garbled. I am sorry for the output format but happens because of that :)

Ah, thanks also for pointing this out, locally I redirect stderr when investigating, e.g. `zee file 2> zee.log`, but even so, as you noticed, the terminal stays stuck in raw mode on panics. Someone [suggested](https://github.com/zee-editor/zee/issues/16#issue-1186951412) to instead use a custom panic handler which resets the terminal -- this seems like a very good idea and I'll certainly have a go at implementing it.

**Comment by wizofe** [comment]
Yes I used the cargo version. OK, please do. Also, a bit of different topic but why there's no search function? :)

**Comment by mcobzarenco** [comment]
Just a quick note that I released a new version (0.2.1) which includes a fix for this, as well as a lot of new goodies. Will get better at documenting it, I promise!

**Comment by mcobzarenco** [comment]
> Also, a bit of different topic but why there's no search function? :)
Haven't come around to implementing yet! :upside_down_face:

**Comment by mcobzarenco** [comment]
>> It's also messing up my shell afterwards
>
> Someone https://github.com/zee-editor/zee/issues/16#issue-1186951412 to instead use a custom panic handler which resets the terminal -- this seems like a very good idea and I'll certainly have a go at implementing it.

Just a note for posterity that I added a custom panic handler in https://github.com/zee-editor/zee/commit/d2cae717f2cc2cd68bf68b918fda80d533b96d09 to print the panic after unwinding and changed the release profile from abort -> unwind to ensure the terminal gets reset from raw mode (and the panic is printed nicely). I do hope it won't be needed, ha :smile:
