### ISSUE TITLE
Alternative grammars

### ISSUE THREAD

**Issue by dmvianna** [zee-editor/zee#37]
Is there a recommended way to install grammars not build by default with `zee --build`?

**Comment by mcobzarenco** [comment]
Thank you for the question! 

Right now it's only possible to configure the available grammars by editing [`modes.ron`](https://github.com/zee-editor/zee/blob/master/zee/modes.ron) and rebuilding the editor. 

I am working on changing this in https://github.com/zee-editor/zee/pull/29 which makes grammars configurable at runtime (e.g. the tree sitter parsers and modes). 

Longer term: a lot more things will be configurable, such as key bindings, themes and I hope eventually using rust/wasm plug-ins to extend zee itself.

**Comment by mcobzarenco** [comment]
See the [configuration](https://github.com/zee-editor/zee#configuration) section in the README and the config.ron file for customising what grammars are used -- both git and local are supported.

Fixed by #29
