### ISSUE TITLE
[Question] Telemetry?

### ISSUE THREAD

**Issue by kevinmatthes** [zee-editor/zee#38]
Hello!

First of all, thank you for this editor!

When trying to install the latest version, this operation failed due to an OpenSSL installation being missing.  What does `zee` need OpenSSL for?  Does `zee` have telemetry features or why is OpenSSL a requirement for the editor?

**Comment by iainh** [comment]
Kevin, 

Not an authoritative answer but looking at the source, `openssl-sys` is pulled in by the 'https' feature (part of the default crate  features) of the `git2` crate which is used by zee for Git repository integration. `git2` doesn't have support for `rustls` as an alternate TLS implementation so there isn't any way around using OpenSSL without stripping Git integration entirely. 

Here is the relevant section of the dependency tree if you are interested: 

```
... 
├── git2 v0.14.2
│   ├── bitflags v1.3.2
│   ├── libc v0.2.124
│   ├── libgit2-sys v0.13.2+1.4.2
│   │   ├── libc v0.2.124
│   │   ├── libssh2-sys v0.2.23
│   │   │   ├── libc v0.2.124
│   │   │   ├── libz-sys v1.1.5
│   │   │   │   └── libc v0.2.124
│   │   │   │   [build-dependencies]
│   │   │   │   ├── cc v1.0.73 (*)
│   │   │   │   └── pkg-config v0.3.25
│   │   │   └── openssl-sys v0.9.72
│   │   │       └── libc v0.2.124
│   │   │       [build-dependencies]
│   │   │       ├── autocfg v1.1.0
│   │   │       ├── cc v1.0.73 (*)
│   │   │       └── pkg-config v0.3.25
│   │   │   [build-dependencies]
│   │   │   ├── cc v1.0.73 (*)
│   │   │   └── pkg-config v0.3.25
│   │   ├── libz-sys v1.1.5 (*)
│   │   └── openssl-sys v0.9.72 (*)
│   │   [build-dependencies]
│   │   ├── cc v1.0.73 (*)
│   │   └── pkg-config v0.3.25
│   ├── log v0.4.16 (*)
│   ├── openssl-probe v0.1.5
│   ├── openssl-sys v0.9.72 (*)
...
```

**Comment by kevinmatthes** [comment]
Thank you for your answer, @iainh.

I was confused about the need for a network library for a text editor but Git integration makes sense.  Since there are some IDEs / text editors which actually have telemetry features incorporated, such as VS Code (where the telemetry level can be configured in the settings), I wondered whether `zee` might have such features, as well.

This answers the question, thank you for your help!
