### ISSUE TITLE
[Bug] Copy and Paste without System Clipboard not Working

### ISSUE THREAD

**Issue by kevinmatthes** [zee-editor/zee#50]
With the latest Nightly Version, it is not possible anymore to copy and paste selections when there is no integration of the system keyboard.  Since the version on crates.io has this feature instead, I would consider its missing a bug.

**Comment by mcobzarenco** [comment]
I am struggling to reproduce this. I just installed `zee` freshly with no extra features, e.g.
```
cargo install --git https://github.com/zee-editor/zee
```

and I seem to be able to copy :thinking: 

![Peek 2022-07-18 23-31](https://user-images.githubusercontent.com/797170/179628209-5a41b5f9-d9d1-45b9-a217-7bdd669e8e53.gif)

**Comment by kevinmatthes** [comment]
I just reinstalled the application from the latest repository state, cleared the configuration (`config.ron` + Tree-Sitter artifacts), reinitialised it and opened two existing C++ source files, one after another.  It did not work.

At least I found a bug in the colour theme I submitted in #44 which I am going to fix.

Do you have clipboard utilities like `parcellite` installed or does your desktop environment provide a clipboard widget?  Do your selections appear there?  Or are you able to paste them in another application, for instance LibreOffice Writer?

**Comment by kevinmatthes** [comment]
Cutting and pasting does also something interesting:  the selection will be inserted again at the position it was taken from.

Did I miss any further dependencies?

**Comment by kevinmatthes** [comment]
I found my mistake.  I am sorry, I switched the keyboard layouts without noticing by accident such that the bindings invoked other commands than expected.

Copying and cutting both work fine, it was just a usage error in the end.  I am sorry.
