### ISSUE TITLE
[Project Idea] Introduce Github discussions, gitter, or similar?

### ISSUE THREAD

**Issue by iainh** [zee-editor/zee#51]
I've been wondering whether there might be value in enabling Github discussions or setting up gitter or something similar to allow for an additional channel of discussion of up coming changes, project development questions, or announcing when you are working on something that isn't ready for a PR to avoid duplicate efforts. Any interest in this? Anything public adds an amount of moderation overhead which might out weigh the value depending how active it is. Perhaps just creating issues and self-assigning (permissions permitting) would work.

**Comment by mcobzarenco** [comment]
That sounds like a grand idea, thinking lowest friction would be Github discussions. Would you be up for helping manage those by any chance?

**Comment by kevinmatthes** [comment]
I created some initial discussion topics, #54 and #56, feel free to contribute.
